function Footer(){
    return(
        <>
        <div>
         <nav className=" container navbar navbar-primary bg-primary p-2 text-center "> this a footer sectin generated by  2025</nav>
        </div>
        
        </>
    );
}
export default Footer;

